exports.months = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
];
exports.bgColor = {
  January: '#382C05',
  February: '#5E4A08',
  March: '#83670B',
  April: '#AA850E',
  May: '#D0A311',
  June: '#EDBC1D',
  July: '#F0C742',
  August: '#F3D268',
  September: '#F6DE8E',
  October: '#F7E3A1',
  November: '#F8E8B4',
  December: '#FAEEC7',
};
